build:
  environment:
    python:
      version: 3.9.9
  dependencies:
    override:
      - pip install mypy==0.971
  nodes:
    coverage:
      dependencies:
        before:
          - make setup
      tests:
        override:
          - command: make coverage
            coverage:
              file: '.coverage'
              format: 'py-cc'