version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/python:3.9.0'
    steps:
      - run: python --version
      - checkout
      - python/load-cache
      - run:
          command: make setup
          name: Setup deps
      - python/save-cache
      - run:
          command: make test
          name: Test

workflows:
  main:
    jobs:
      - test
