version: 2.1

jobs:
  test:
    build:
      docker:
        - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/load-cache
      - run:
          command: make setup
          name: Setup deps
      - python/save-cache
      - run:
          command: make test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
