name: Benchmark

on: [push]

jobs:
  build:
    name: bench-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make setup
    - name: Run Bechmarking
      id: run_benchmark
      run: |
        make benchmark
    - uses: actions/upload-artifact@v4
      name: Save Benchmarks
      if: success() || steps.run_benchmark.conclusion == 'failure'
      with:
        name: benchmark-results
        path: .benchmarks/